basePath: /api/v1
definitions:
  main.event:
    properties:
      date:
        type: string
      key:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: bilenkomaria02@gmail.com
    name: API Support
  description: API for the marathon service. Provides basic methods for managing a
    marathon
  license:
    name: MIT
    url: https://git.tjump.ru/mariya.bilenko/med
  termsOfService: http://swagger.io/terms/
  title: Marathon API
  version: "1.0"
paths:
  /marathon:
    get:
      consumes:
      - application/json
      description: search for an event by key in the database
      operationId: get-string-by-int
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.event'
      summary: Find event by key
    post:
      consumes:
      - application/json
      description: add new event
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Add new event
swagger: "2.0"
