basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: bilenkomaria02@gmail.com
    name: API Support
  description: API for the marathon service. Provides basic methods for managing a
    marathon.
  license:
    name: MIT
    url: https://git.tjump.ru/mariya.bilenko/med
  termsOfService: http://swagger.io/terms/
  title: Marathon API
  version: "1.0"
paths: {}
swagger: "2.0"
