version: "3.8"
services:
  db:
    image: "postgres:13"
    container_name: db
    working_dir: /usr/appl
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12340
      - POSTGRES_DB=marathon
    networks:
      - marathon

  server:
    container_name: appl
    build:
      context: ../Med
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - marathon


networks:
  marathon:
    driver: bridge